### ISSUE TITLE
Unhandled Exception: System.SystemException

### ISSUE THREAD

**Issue by yeucodonvn** [liulilittle/VEthernet#7]
i have build VEthernet with VS2022
when running. tool cannot start with error
"Unhandled Exception: System.SystemException: Unable to open netif specifying componentId
   at VEthernet.Net.TapTap2Socket..ctor(Boolean subnetstack, Int32 port, NetworkStatistics networkStatistics)
   at tun2socks.Socks5Ethernet..ctor(IPEndPoint proxyServer, IPAddress[] dnsAddresses, Boolean productMode, Boolean protectDefaultGateway, String user, String password, String bypassIplist, NetworkStatistics networkStatistics) in F:\C#\VEthernet-main\tun2socks\Socks5Ethernet.cs:line 31
   at tun2socks.Program.Main(String[] args) in F:\C#\VEthernet-main\tun2socks\Program.cs:line 165"

OS windows 10 x64 1909
![image](https://user-images.githubusercontent.com/18210504/194777867-ae726bb3-7351-4351-a3f0-91090c28c115.png)

**Comment by liulilittle** [comment]
Didn't you see the error code above?

1. You must install TAP-Windows Driver on your operating system.

2. Open "TAP-Windows Driver" must be exclusive (that is, others do not allow open the virtual network card)
